import "./globals.css";
import { scratchyFont } from "./fonts";
import { sometypeMonoFont } from "./fonts";
import { dirtyStainsFont } from "./fonts";
import HeaderApp from "@/components/html/HeaderApp";
import FooterApp from "@/components/html/FooterApp";
import { ThemeProvider } from "@/contexts/ThemeContext";
import ThemeToggle from "@/components/ui/theme-toggle";
import AppBackground from "@/components/AppBackground";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" className="overflow-x-hidden overflow-y-auto">
      <body
        className={`${scratchyFont.variable} ${sometypeMonoFont.variable} ${dirtyStainsFont.variable} antialiased overflow-x-hidden overflow-y-auto`}
      >
        <ThemeProvider>
          <AppBackground />
          {/* <ThemeToggle /> */}
          <div className="relative min-h-screen flex flex-col overflow-x-hidden overflow-y-auto">
            {children}
            {/* Footer */}
            {/* <FooterApp /> */}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}