import "./globals.css";
import { scratchyFont } from "./fonts";
import { sometypeMonoFont } from "./fonts";
import { dirtyStainsFont } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${scratchyFont.variable} ${sometypeMonoFont.variable} ${dirtyStainsFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
